--  28 Slots Avalable For Serpent Current Whitelist Goes for 170$ USD, Bitcoin or Litecoin  --
-- Created By The Works Of Gamesneeze.cc/Atlanta Assist and Much others
-- Comes With Private PC Cleaner/PC Check Bypass Thats Exlusive to Buyers Only --
-- Comes With Exlusive Programs Like Our Auto PS Joiner and more -- 
-- 25x Da hood Stars Crewleaders + Da hood Stars -- 
-- Never Public Nor Released Fully --
-- CURRENT AVALABLE WHITELISTS 28/40 -- 

--██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████--        yes the N is fucked up
--█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░███░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█░░░░░░░░░░░░░░█--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░░░░░░░░░██░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█--
--█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀▄▀▄▀▄▀▄▀░░██░░▄▀░░█░░░░░░▄▀░░░░░░█--
--█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░░░███░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█████████░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█████░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░██░░▄▀░░░░░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░░░░░█░░▄▀░░█████████░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀▄▀▄▀▄▀▄▀░░█████░░▄▀░░█████--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀▄▀▄▀░░█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░░░░░░░░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░██░░░░░░░░░░█░░░░░░█████████░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█████░░░░░░█████--
--██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████--
--.🅒🅒--
-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- // Main Log V.3.8 Serpent.cc 
-- // Soon making Camlock Range Stuff
-- // Starting On V4
-- // ADDED RAPID FIRE 
-- // ADDED LUA INJECTION FOR GUI
-- // ADDED MORE STYLES FOR SILENT AIM
-- // REDID ANTI CURVE 
-- // ADDED IF ERROR THEN KICK
-- // ADDED ERROR LOGGER

-- IMPORTANT MUST READ 
-- // NOTE: WHEN DOING FOVSHAPED FOR SILENT AIM RANGE SETTINGS YOU HAVE TO ENABLE THE SHAPE YOU WANT TOO USE IN THE SILENT AIM FOV SECTION THIS CAN APPLY FOR MULTIPLE
-- // NOTE: ALL HVH FEATURES ARE INSIDE THE GUI INCLUDING CYSNC AND BULLET TP
-- // NOTE: ALL FEATURES ARE UNIVERSAL BTW FOR ALL HOOD GAMES, ALSO THE ANTI GROUND SHOTS SETS KEEP THEM THE SAME OR SCRIPT WILL BREAK
-----------------------------------------------------------------------------------------------------------------------------------------------------------

getgenv().Serpent = {
    ['StartUP'] = {
        ['ScriptKey'] = "Put your Lua Armour Key Inside here",
        ['GUI'] = true, -- Main
        ['LoadSeconds'] = 1, -- How many Seconds you Want the Script Too Load
        ['LoadKeybind'] = '', -- Keybind For the Script To load Good for Closet cheating
        ['Intro'] = true,
        ['MuteBoomBox'] = false,
        ['RemoveSeats'] = false
    },
    ['Optimizer'] = {
        ['FpsBoost'] = true, -- Updated 85% More FPS Boost
        ['AutoLowGFX'] = false,
        ['DestroyF9Console'] = false,
        ['UWPBooster'] = nil,
        ['GreySky'] = false,
        ['RemoveShadows'] = false
    }
    ['Universal'] = {
       ['GameID'] = "", -- Enter Your Game ID You want to Play, Examples: HoodCustoms = 9825515356, Hood Modded = 5602055394, leave blank for da hood
       ['AdonisBypass'] = true,
       ['HoodCustomsACBypass'] = true,
       ['HoodCustomsVectorSilentFix'] = true -- Keep on if Your going in hood customs
    },
    ['Support'] = { -- KEEP ON NILL FOR EXECUTORS THAT ARE DOWN
        ['Solara'] = true,
        ['Krampus'] = nil,
        ['FluxusUWP'] = nil,
        ['Evon'] = nil,
        ['KRNL'] = nil,
        ['Synapse'] = nil,
        ['ScriptWare'] = nil,
        ['Electron'] = nil,
        ['Celery'] = true,
        ['Fluxus'] = nil,
        ['ElectronUWP'] = nil,
        ['A8q*idsa81dgdjh'] = true
    },
    ['Checks'] = {
        ['WallCheck'] = true,
        ['FriendCheck'] = false,
        ['CrewCheck'] = false,
        ['ForceFieldCheck'] = true,
        ['KnockedCheck'] = true,
        ['GrabbedCheck'] = true,
        ['ModCheck'] = true,
        ['ExploiterCheck'] = true,

        ['Notifications'] = {
            ['LoadTimeStartup'] = true,
            ['ModCheckNotifications'] = true,
            ['ExploiterCheckNotifications'] = true,
            ['TargetAimNotifications'] = false,
            ['SilentAimNotifications'] = false,
            ['CamLockNotifications'] = false,
            ['AntiAimNotifications'] = false,
            ['FFLAGNotifications'] = false,
            ['PanicNotifications'] = true,
            ['FrameSkipNotifications'] = false,
            ['NotificationMode'] = "Roblox" -- Xaxa, Roblox
        }
    },
    ['Streamable'] = {
        ['Enabled'] = true,
        ['Keybind'] = "",
        ['ESP'] = true,
        ['FOV'] = true,
        ['RaidAwareness'] = true,
        ['KeybindList'] = true
    },
    ['SilentAim'] = {
        ['Enabled'] = true,
        ['Keybind'] = "L",
        ['POS'] = ['AutoDetect'],
        ['VisualizePoint'] = false,
        ['Hitpart'] = 'HumanoidRootPart',
        ['AntiGroundShots'] = {
            ['X'] = 0.1;
            ['Y'] = 0.4
        },
        ['AntiCurve'] = {
            ['Enabled'] = true,
            ['VelocityControl'] = {
                ['AdvancedVelocity'] = true,
                ['X'] = 0.5,
                ['Y'] = 0.3
            },
            ['DeltaControl'] = {
                ['DeltaPattern'] = true,
                ['Amount'] = 100
            }
        },
        ['BulletManiputlation'] = {
         ['Postition'] = 'All',
         Remotes = local Path = game:GetService("ReplicatedStorage").MainEvent -- DONT EDIT
            return Arguments, Path
        end
        ['Style'] = 'Sine' -- Elastic, Sine, Linear, Quad
        },
        ['Mode'] = {
            ['AdvancedClosest'] = true, -- A More Legit Version Of Closest Point Super Advanced Points and Reductions Rates
            ['ClosestPoint'] = false, -- Closest Point To your Cursor
            ['ClosestPart'] = false, -- Uses All 16 Hitparts Closest To your Cursor
            ['Normal'] = false -- Uses Only One Hitpart Chosen Closest to your Cursor
        },
        ['Settings'] = {
            ['OverrideXAxis'] = "Default", -- Default, Minimal, Partial, SmoothOut
            ['OverrideYAxis'] = "Default", -- Default, Minimal, Partial, SmoothOut
            ['OverrideZAxis'] = "Default", -- Default, Minimal, Partial, SmoothOut
            ['ClosestPointReductionRate'] = 20,
            ['HitChance'] = 100,
            ['AutoPrediction'] = false,
            ['AutoPredictionMode'] = 'V.8', -- V.1 V.2 V.3 V.4 V.5 V.6 V.7 V.8
            ['ClosestPointOffsets'] = {
                ['UseOffsets'] = false,
                ['XOffset'] = 0,
                ['YOffset'] = 0
            }
        },
        ['FovModes'] = {
            ['Normal'] = true, -- Simple Circlular FOV
            ['Box'] = false, -- Box that Surrounds your Target and Acts as A Field of View
            ['PlayerFOV'] = false -- Most Legit and Advanced FOV as it acts as a Outline Onto your Selected Silent aim Target Acting as a Field Of View
        },
        ['Normal'] = {
            ['Show'] = true,
            ['Size'] = 50,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Sticky'] = false,
            ['NormalShaped'] = {
                ['Hexagon'] = false,
                ['Triangle'] = false,
                ['Octigon'] = false
            }
        },
        ['Box'] = {
            ['Show'] = false,
            ['Sticky'] = true, -- Recommend
            ['Widith'] = 100,
            ['Height'] = 100,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Predicted'] = true -- Makes the FOV Follow with the Prediction Of your Silent aim
        },
        ['PlayerFOV'] = { -- GUIDE: Player FOV Might seem Tricky at First But it's Just Roblox Avatar Scales (Current Settings Recommended)
            ['Show'] = false,
            ['Height'] = 90/100,
            ['Widith'] = 70/100,
            ['Head'] = 95/100,
            ['Proportions'] = 5/100
        }
    },
    ['TargetAim'] = {
        ['Enabled'] = false,
        ['AirShotFunction'] = true,
        ['Keybind'] = "",
        ['Prediction'] = 0.124878157348769238732897353555555,
        ['AirShotPrediction'] = 0.12485,
        ['Hitpart'] = "Head", -- You can Use All 16 Hitparts For this
        ['AntiGroundShots'] = true,
        ['Size'] = 70, -- FOV
        ['Color'] = Color3fromRGB(200, 1, 200),
        ['Filled'] = false,
        ['Thickness'] = 0.2,
        ['Transparency'] = 0.5,
        ['HighlightTargetedPlayer'] = true
    },
    ['Camlock'] = {
        ['Enabled'] = true,
        ['Keybind'] = "C",
        ['HoldMode'] = false,
        ['MouseMode'] = false,
        ['MouseBind'] = Enum.UserInputType.MouseButton1,
        ['CamlockChecks'] = {
            ['TypeCheck'] = false,
            ['DisableOnThirdPerson'] = false,
            ['DisableOnReload'] = false,
            ['GunCheck'] = false
        }, 
        ['Settings'] = {
            ['ClosestPoint'] = false,
            ['ClosetPart'] = false,
            ['Normal'] = true, -- One Hitpart
            ['Hitpart'] = "UpperTorso",
            ['AirShotHitpart'] = "Head",
            ['CamlockOffsets'] = {
                ['UseOffsets'] = false,
                ['XOffset'] = 0,
                ['YOffset'] = 0
            }
            ['PredictionSettings'] = {
                ['PredictionX'] = 0.135, -- Main Prediction
                ['PredictionY'] = 0.135
            }
        },
        ['FovSettings'] = {
            ['Show'] = true,
            ['Size'] = 50,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Deadzone'] = false,
            ['DeadzoneSize'] = 15
        },
        ['CamlockModes'] = {
            ['Easing'] = true,
            ['Bezier'] = false,
            ['Hyperbola'] = false,
            ['Cardioid'] = false
        },
        ['EasingSettings'] = {
            ['EasingStyle'] = "Linear",
            ['AirEasingStyle'] = "Sine",
            ['EasingDirection'] = "InOut"
        },
        ['BezierSettings'] = {
            ['T_Threshold'] = 0.99941,
            ['CurvePoints'] = Vector2.new(0, 0) -- X, Y
        },
        ['Hyperbola'] = {
            ['Hyperbola_Sensitivity'] = 4, -- Smoothness
            ['HyperbolaFrequency'] = 0.5,
            ['ActOnRecoil'] = true
        },
        ['Cardioid'] = {
            ['CardioidX'] = 1,
            ['CardioidY'] = 7,
            ['CardioidFrequency'] = 0.5
        },
        ['Other'] = {
            ['FrameSkips'] = false,
            ['FrameSkipKeybind'] = "",
            ['ShakeSettings'] = {
                ['Shake'] = false,
                ['Shake_X'] = 1,
                ['Shake_Y'] = 1,
                ['Shake_Z'] = 1,
                ['ShakeOffsetX'] = 0,
                ['ShakeOffsetY'] = 0
            }
        }
    },
    ['TriggerBot'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['MouseMode'] = false,
        ['MouseBind'] = Enum.UserInputType.MouseButton2,
        ['DisableWhenKnife'] = true,
        ['HoldMode'] = false,
        ['PredictionMode'] = {
            ['Enabled'] = true,
            ['Prediction'] = 0.12,
        },
        ['TriggerBotFOV'] = {
            ['UseFov'] = true,
            ['UseBox'] = false,
            ['BoxWidith'] = 55,
            ['BoxHeight'] = 55,
            ['Size'] = 30,
        },
        ['TriggerBotRangeSettings'] = {
            ['Enabled'] = false,

            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal"
        }
    },
    ['RangeFOVSilent'] = {
        ['Enabled'] = false,
        ['Shotguns'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,

            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100,

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal"

        },
        ['Pistols'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,

            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100,

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal"
        },
        ['Automatics'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,

            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal"
        }
    },
    ['Misc'] = {
        ['PanicKey'] = "",
        ['CFrame'] = "", -- 185 Speed
        ['Fly'] = "", -- 145 Speed
    },
    ['Visuals'] = { -- Inside GUI Has Customizable Colors Plus Visualizer
        ['Enabled'] = false,
        ['NameESP'] = false,
        ['BoundingBox'] = false,
        ['HealthBar'] = false,
        ['HealthNumber'] = false,
        ['HeadDot'] = false,
        ['OffscreenArrows'] = false,
        ['GunESP'] = false,
        ['GunChams'] = false,
        ['PlayerChams'] = false,
        ['AnimatedESP'] = false,
        ['FriendlyESP'] = false, -- Highlights Friends
        ['TargetESP'] = false, -- Highlights Targeted Players
        ['TargetedPlayerName'] = "Byfron", -- Username
        ['AnimateESP'] = false,
        ['PlayerDistance'] = false
    },
    ['RaidAwareness'] = {
        ['Enabled'] = false,
        ['Keybind'] = "", -- Toggle Onto your Targeted Player
        ['KillSwitch'] = "",

        ['Username1'] = "",
        ['Username2'] = "",
        ['Username3'] = "",
        ['Username4'] = "",
        ['Username5'] = "",
        ['Username6'] = "",
        ['Username7'] = "",
        ['Username8'] = "",
        ['Username9'] = "",
        ['Username10'] = ""
    },
    ['AntiAim'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['AntiLockMode'] = "PredictionBreaker" -- PredictionBreaker, InvisibleDesync, Desync, Underground, Sky
    },
    ['FFLAG'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['FFLAGMode'] = "InvisibleDesync" -- Underground, InvisibleDesync, Jitter
    },
    ['RapidFire'] = { -- more Universal within Gui
        ['Enabled'] = false,
        ['Rate'] = 10
    },
    -- Error loggers If you Know you know I'd Recommend too not touch
    -- Credits too Stefanuk for Helping me On this
    -- checks for any errors
    export type ErrorLogger = {
        ErrorCheck: boolean | "error" | "kick",
        DisableIfSpeedAbove: 10, -- Recommend too Keep On 10 Test For yourself
        ['Enabled'] = false,
        ['Print'] = false, -- Would Use if Your testing
        ['PrintMessage'] = "ur lock is ass nigga get serpent",
        ['Delay'] = 1 -- In seconds
    },
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/e14209cacb6973d3e605234db8583c52.lua"))()  
