--  37 Slots Avalable For Serpent Current Whitelist Goes for 170$ USD, Bitcoin or Litecoin  --
-- Never Public Nor Released Fully --
-- CURRENT AVALABLE WHITELISTS 37/40 -- 

--██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████--        yes the N is fucked up
--█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░███░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█░░░░░░░░░░░░░░█--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░░░░░░░░░██░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█--
--█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀▄▀▄▀▄▀▄▀░░██░░▄▀░░█░░░░░░▄▀░░░░░░█--
--█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░░░███░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█████████░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█████░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░██░░▄▀░░░░░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░░░░░█░░▄▀░░█████████░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀▄▀▄▀▄▀▄▀░░█████░░▄▀░░█████--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀▄▀▄▀░░█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░░░░░░░░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░██░░░░░░░░░░█░░░░░░█████████░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█████░░░░░░█████--
--██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████--
--.🅒🅒--
-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- // Main Log V.2.5 Serpent.cc 
-- // Soon making Camlock Range Stuff
-- // Added Hold Mode for Triggerbot
-- // Added Support to Private executor "A8q*idsa81dgdjh" (Not actual name Btw)
-- // NOTE: ALL FEATURES ARE UNIVERSAL BTW FOR ALL HOOD GAMES, ALSO THE ANTI GROUND SHOTS SETS KEEP THEM THE SAME OR SCRIPT WILL BREAK
-----------------------------------------------------------------------------------------------------------------------------------------------------------

getgenv().Serpent = {
    ['StartUP'] = {
        ['ScriptKey'] = "Put your Lua Armour Key Inside here",
        ['GUI'] = true, -- Main
        ['LoadSeconds'] = 1, -- How many Seconds you Want the Script Too Load
        ['LoadKeybind'] = '', -- Keybind For the Script To load Good for Closet cheating
        ['FPSBOOST'] = true,
        ['UWPBooster'] = nill,
        ['DestroyF9Console'] = false,
        ['Intro'] = true,
        ['MuteBoomBox'] = false,
        ['RemoveSeats'] = false
    },
    ['Universal'] = {
       ['GameID'] = "", -- Enter Your Game ID You want to Play, Examples: HoodCustoms = 9825515356, Hood Modded = 5602055394
       ['AdonisBypass'] = true,
       ['HoodCustomsACBypass'] = true
    },
    ['Support'] = { -- KEEP ON NILL FOR EXECUTORS THAT ARE DOWN
        ['Solara'] = true,
        ['Krampus'] = nill,
        ['FluxusUWP'] = nill,
        ['Evon'] = nill,
        ['KRNL'] = nill,
        ['Synapse'] = nill,
        ['ScriptWare'] = nill,
        ['Electron'] = nill,
        ['Celery'] = true,
        ['Fluxus'] = nill,
        ['ElectronUWP'] = nill,
        ['A8q*idsa81dgdjh'] = true
    },
    ['Checks'] = {
        ['WallCheck'] = true,
        ['FriendCheck'] = false,
        ['CrewCheck'] = false,
        ['ForceFieldCheck'] = true,
        ['KnockedCheck'] = true,
        ['GrabbedCheck'] = true,
        ['ModCheck'] = true,
        ['ExploiterCheck'] = true,

        ['Notifications'] = {
            ['LoadTimeStartup'] = true,
            ['ModCheckNotifications'] = true,
            ['ExploiterCheckNotifications'] = true,
            ['TargetAimNotifications'] = false,
            ['SilentAimNotifications'] = false,
            ['CamLockNotifications'] = false,
            ['AntiAimNotifications'] = false,
            ['FFLAGNotifications'] = false,
            ['PanicNotifications'] = true,
            ['FrameSkipNotifications'] = false,
            ['NotificationMode'] = "Roblox" -- Xaxa, Roblox
        }
    },
    ['SilentAim'] = {
        ['Enabled'] = true,
        ['Keybind'] = "L",
        ['POS'] = ['UpedateMousePOS'],
        ['VisualizePoint'] = false,
        ['Hitpart'] = 'HumanoidRootPart',
        ['AntiGroundShots'] = {
            ['X'] = 0.1;
            ['Y'] = 0.4
        },
        ['AntiCurve'] = {
            ['Enabled'] = true,
            ['AdvancedVelocity'] = true,
            ['DeltaPattern'] = true,
        },
        ['BulletManiputlation'] = {
         ['Postition'] = 'All',
         Remotes = local Path = game:GetService("ReplicatedStorage").MainEvent -- DONT EDIT
            return Arguments, Path
        end
        ['Style'] = 'Sine'
        },
        ['Mode'] = {
            ['AdvancedClosest'] = true, -- A More Legit Version Of Closest Point Super Advanced Points and Reductions Rates
            ['ClosestPoint'] = false, -- Closest Point To your Cursor
            ['ClosestPart'] = false, -- Uses All 16 Hitparts Closest To your Cursor
            ['Normal'] = false -- Uses Only One Hitpart Chosen Closest to your Cursor
        },
        ['Settings'] = {
            ['OverideXAxis'] = true,
            ['OverideYAxis'] = true,
            ['ClosestPointReductionRate'] = 20,
            ['HitChance'] = 100,
            ['AutoPrediction'] = false,
            ['AutoPredictionMode'] = 'V.8' -- V.1 V.2 V.3 V.4 V.5 V.6 V.7 V.8
        },
        ['FovModes'] = {
            ['Normal'] = true, -- Simple Circlular FOV
            ['Box'] = false, -- Box that Surrounds your Target and Acts as A Field of View
            ['PlayerFOV'] = false -- Most Legit and Advanced FOV as it acts as a Outline Onto your Selected Silent aim Target Acting as a Field Of View
        },
        ['Normal'] = {
            ['Show'] = true,
            ['Size'] = 50,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Sticky'] = false,
            ['Hexagon'] = false,
            ['Triangle'] = false,
            ['Octigon'] = false
        },
        ['Box'] = {
            ['Show'] = false,
            ['Widith'] = 100,
            ['Height'] = 100,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Predicted'] = true -- Makes the FOV Follow with the Prediction Of your Silent aim
        },
        ['PlayerFOV'] = { -- GUIDE: Player FOV Might seem Tricky at First But it's Just Roblox Avatar Scales (Current Settings Reccomended)
            ['Show'] = false,
            ['Height'] = 90/100,
            ['Widith'] = 70/100,
            ['Head'] = 95/100,
            ['Proportions'] = 5/100
        }
    },
    ['TargetAim'] = {
        ['Enabled'] = false,
        ['AirShotFunction'] = true,
        ['Keybind'] = "",
        ['Prediction'] = 0.124878157348769238732897353555555,
        ['AirShotPrediction'] = 0.12485,
        ['Hitpart'] = "Head", -- You can Use All 16 Hitparts For this
        ['AntiGroundShots'] = true,
        ['Size'] = 70, -- FOV
        ['Color'] = Color3fromRGB(200, 1, 200),
        ['Filled'] = false,
        ['Thickness'] = 0.2,
        ['Transparency'] = 0.5,
        ['HighlightTargetedPlayer'] = true
    },
    ['Camlock'] = {
        ['Enabled'] = true,
        ['Keybind'] = "C",
        ['HoldMode'] = false,
        ['MouseMode'] = false,
        ['MouseBind'] = Enum.UserInputType.MouseButton1,
        ['CamlockChecks'] = {
            ['TypeCheck'] = false,
            ['DisableOnThirdPerson'] = false,
            ['DisableOnReload'] = false,
            ['GunCheck'] = false
        }, 
        ['Settings'] = {
            ['Prediction'] = 0.135,
            ['ClosestPoint'] = false,
            ['ClosetPart'] = false,
            ['Normal'] = true, -- One Hitpart
            ['Hitpart'] = "UpperTorso",
            ['AirShotHitpart'] = "Head"
        },
        ['FovSettings'] = {
            ['Show'] = true,
            ['Size'] = 50,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Deadzone'] = false,
            ['DeadzoneSize'] = 15
        },
        ['CamlockModes'] = {
            ['Easing'] = true,
            ['Bezier'] = false,
            ['Hyperbola'] = false,
            ['Cardioid'] = false
        },
        ['EasingSettings'] = {
            ['EasingStyle'] = "Linear",
            ['AirEasingStyle'] = "Sine",
            ['EasingDirection'] = "InOut"
        },
        ['BezierSettings'] = {
            ['T_Threshold'] = 0.99941,
            ['CurvePoints'] = Vector2.new(0, 0) -- X, Y
        },
        ['Hyperbola'] = {
            ['Hyperbola_Sensitivity'] = 4, -- Smoothness
            ['HyperbolaFrequency'] = 0.5,
            ['ActOnRecoil'] = true
        },
        ['Cardioid'] = {
            ['CardioidX'] = 1,
            ['CardioidY'] = 7,
            ['CardioidFrequency'] = 0.5
        },
        ['Other'] = {
            ['Shake'] = false,
            ['Shake_X'] = 1,
            ['Shake_Y'] = 1,
            ['Shake_Z'] = 1,
            ['FrameSkips'] = false,
            ['FrameSkipKeybind'] = ""
        }
    },
    ['TriggerBot'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['MouseMode'] = false,
        ['MouseBind'] = Enum.UserInputType.MouseButton2,
        ['DisableWhenKnife'] = true,
        ['HoldMode'] = false,
        ['PredictionMode'] = {
            ['Enabled'] = true,
            ['Prediction'] = 0.12,
        },
        ['TriggerBotFOV'] = {
            ['UseFov'] = true,
            ['UseBox'] = false,
            ['BoxWidith'] = 55,
            ['BoxHeight'] = 55,
            ['Size'] = 30,
        },
        ['TriggerBotRangeSettings'] = {
            ['Enabled'] = false,
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,
            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,
            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10
        }
    },
    ['RangeFOVSilent'] = {
        ['Enabled'] = false,
        ['Shotguns'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,
            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,
            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,
            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100,
        },
        ['Pistols'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,
            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,
            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,
            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100,
        },
        ['Automatics'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,
            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,
            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,
            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100
        }
    },
    ['Misc'] = {
        ['PanicKey'] = "",
        ['CFrame'] = "", -- 185 Speed
        ['Fly'] = "", -- 145 Speed
        ['AntiLock'] = "", -- Uses Private Desync
    },
    ['Visuals'] = { -- Inside GUI Has Customizable Colors Plus Visualizer
        ['Enabled'] = false,
        ['NameESP'] = false,
        ['BoundingBox'] = false,
        ['HealthBar'] = false,
        ['HealthNumber'] = false,
        ['HeadDot'] = false,
        ['OffscreenArrows'] = false,
        ['GunESP'] = false,
        ['GunChams'] = false,
        ['PlayerChams'] = false,
        ['AnimatedESP'] = false,
        ['FriendlyESP'] = false, -- Highlights Friends
        ['TargetESP'] = false, -- Highlights Targeted Players
        ['TargetedPlayerName'] = "Byfron" -- Username
    },
}
 
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/e14209cacb6973d3e605234db8583c52.lua"))()  
