--  24 Slots Avalable For Serpent Current Whitelist Goes for 140$ USD, Bitcoin or Litecoin  --
-- Created By The Works Of Gamesneeze.cc/Atlanta Assist and Much others
-- Comes With Private PC Cleaner/PC Check Bypass Thats Exlusive to Buyers Only --
-- Comes With Exlusive Programs Like Our Auto PS Joiner and more -- 
-- 25x Da hood Stars Crewleaders + Da hood Stars -- 
-- Never Public Nor Released Fully --
-- CURRENT AVALABLE WHITELISTS 24/40 -- 

--██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████--        yes the N is fucked up
--█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░░░███░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█░░░░░░░░░░░░░░█--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░░░░░░░░░██░░▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█--
--█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀▄▀▄▀▄▀▄▀░░██░░▄▀░░█░░░░░░▄▀░░░░░░█--
--█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░▄▀░░███░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀▄▀░░███░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░░░███░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░██░░▄▀░░█████░░▄▀░░█████--
--█████████░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█████░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░██░░▄▀░░░░░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░░░░░█░░▄▀░░█████████░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀▄▀▄▀▄▀▄▀░░█████░░▄▀░░█████--
--█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀▄▀▄▀░░█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░░░░░░░░░▄▀░░█████░░▄▀░░█████--
--█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░██░░░░░░░░░░█░░░░░░█████████░░░░░░░░░░░░░░█░░░░░░██████████░░░░░░█████░░░░░░█████--
--██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████--
--.🅒🅒--
-----------------------------------------------------------------------------------------------------------------------------------------------------------
-- // Main Log V.4 Serpent.cc 
-- // COMPLETED V4
-- // NEW UPDATED GUI 
-- // TRASHTALK
-- // FEATURE LIST
-- // ADDED DESTROY CHEATERS
-- // UPDATED RESOLVER METHOD
-- // ADDED PREDICTION ANALYZER

-- IMPORTANT MUST READ 
-- // NOTE: WHEN DOING FOVSHAPED FOR SILENT AIM RANGE SETTINGS YOU HAVE TO ENABLE THE SHAPE YOU WANT TOO USE IN THE SILENT AIM FOV SECTION THIS CAN APPLY FOR MULTIPLE
-- // NOTE: ALL HVH FEATURES ARE INSIDE THE GUI INCLUDING CYSNC AND BULLET TP
-- // NOTE: ALL FEATURES ARE UNIVERSAL BTW FOR ALL HOOD GAMES, ALSO THE ANTI GROUND SHOTS SETS KEEP THEM THE SAME OR SCRIPT WILL BREAK
-- // Resolver Explaination: Linear Is the Best Currently uses a Custom Force Applied onto a constraint.
-- If you want Too learn More https://create.roblox.com/docs/reference/engine/classes/LinearVelocity#PrimaryTangentAxis , https://create.roblox.com/docs/reference/engine/classes/LinearVelocity
-----------------------------------------------------------------------------------------------------------------------------------------------------------

getgenv().Serpent = {
    ['StartUP'] = {
        ['ScriptKey'] = "Put your Lua Armour Key Inside here",
        ['Version'] = "V3.9.9" -- V3.9.4, V3.9.1 Hits more, V3.9.9 Most updated
        ['GUI'] = true, -- Main
        ['LoadSeconds'] = 1, -- How many Seconds you Want the Script Too Load
        ['LoadKeybind'] = '', -- Keybind For the Script To load Good for Closet cheating
        ['Intro'] = true,
        ['MuteBoomBox'] = false,
        ['RemoveSeats'] = false
    },
    ['Optimizer'] = {
        ['FpsBoost'] = true, -- Updated 85% More FPS Boost
        ['AutoLowGFX'] = false,
        ['DestroyF9Console'] = false,
        ['UWPBooster'] = nil,
        ['GreySky'] = false,
        ['RemoveShadows'] = false
    }
    ['Universal'] = {
       ['GameID'] = "", -- Enter Your Game ID You want to Play, Examples: HoodCustoms = 9825515356, Hood Modded = 5602055394, leave blank for da hood
       ['AdonisBypass'] = true,
       ['HoodCustomsACBypass'] = true,
       ['HoodCustomsVectorSilentFix'] = true -- Keep on if Your going in hood customs
    },
    ['Support'] = { -- KEEP ON NILL FOR EXECUTORS THAT ARE DOWN
        ['Solara'] = true,
        ['Wave'] = true,
        ['Krampus'] = nil,
        ['FluxusUWP'] = nil,
        ['Evon'] = nil,
        ['KRNL'] = nil,
        ['Synapse'] = nil,
        ['ScriptWare'] = nil,
        ['Electron'] = nil,
        ['Celery'] = nil,
        ['Fluxus'] = nil,
        ['ElectronUWP'] = nil,
        ['A8q*idsa81dgdjh'] = true
    },
    ['Checks'] = {
        ['WallCheck'] = true,
        ['FriendCheck'] = false,
        ['CrewCheck'] = false,
        ['ForceFieldCheck'] = true,
        ['KnockedCheck'] = true,
        ['GrabbedCheck'] = true,
        ['ModCheck'] = true,
        ['ExploiterCheck'] = true,

        ['Notifications'] = {
            ['LoadTimeStartup'] = true,
            ['ModCheckNotifications'] = true,
            ['ExploiterCheckNotifications'] = true,
            ['TargetAimNotifications'] = false,
            ['SilentAimNotifications'] = false,
            ['CamLockNotifications'] = false,
            ['AntiAimNotifications'] = false,
            ['FFLAGNotifications'] = false,
            ['PanicNotifications'] = true,
            ['FrameSkipNotifications'] = false,
            ['NotificationMode'] = "Roblox", -- Xaxa, Roblox
            ['TrashTalkNotifications'] = true,
            ['StreamableModeNotifications'] = true,
            ['DestroyCheatersNotifications'] = true
        }
    },
    ['Streamable'] = {
        ['Enabled'] = true,
        ['Keybind'] = "",
        ['ESP'] = true,
        ['FOV'] = true,
        ['RaidAwareness'] = true,
        ['KeybindList'] = true
    },
    ['SilentAim'] = {
        ['Enabled'] = true,
        ['Keybind'] = "L",
        ['POS'] = ['AutoDetect'],
        ['VisualizePoint'] = false,
        ['Hitpart'] = 'HumanoidRootPart',
        ['AntiGroundShots'] = {
            ['X'] = 0.1;
            ['Y'] = 0.4
        },
        ['AntiCurve'] = {
            ['Enabled'] = true,
            ['VelocityControl'] = {
                ['AdvancedVelocity'] = true,
                ['X'] = 0.6,
                ['Y'] = 0.5
            },
            ['DeltaControl'] = {
                ['DeltaPattern'] = true,
                ['Amount'] = 100 -- Stableness In %
            }
        },
        ['BulletManiputlation'] = {
         ['Postition'] = 'All',
         Remotes = local Path = game:GetService("ReplicatedStorage").MainEvent -- DONT EDIT
            return Arguments, Path
        end
        ['Style'] = 'Sine' -- Elastic, Sine, Linear, Quad
        },
        ['Mode'] = {
            ['AdvancedClosest'] = true, -- A More Legit Version Of Closest Point Super Advanced Points and Reductions Rates
            ['ClosestPoint'] = false, -- Closest Point To your Cursor
            ['ClosestPart'] = false, -- Uses All 16 Hitparts Closest To your Cursor
            ['Normal'] = false -- Uses Only One Hitpart Chosen Closest to your Cursor
        },
        ['Settings'] = {
            ['OverrideXAxis'] = "Default", -- Default, Minimal, Partial, SmoothOut
            ['OverrideYAxis'] = "Default", -- Default, Minimal, Partial, SmoothOut
            ['OverrideZAxis'] = "Default", -- Default, Minimal, Partial, SmoothOut
            ['ClosestPointReductionRate'] = 20,
            ['Prediction'] = 0.129,
            ['HitChance'] = 100,
            ['ClosestPointOffsets'] = {
                ['UseOffsets'] = false,
                ['XOffset'] = 0,
                ['YOffset'] = 0
            }
        },
        ['FovModes'] = {
            ['Normal'] = true, -- Simple Circlular FOV
            ['Box'] = false, -- Box that Surrounds your Target and Acts as A Field of View
            ['PlayerFOV'] = false -- Most Legit and Advanced FOV as it acts as a Outline Onto your Selected Silent aim Target Acting as a Field Of View
        },
        ['Normal'] = {
            ['Show'] = true,
            ['Size'] = 50,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Rainbow'] = false,
            ['PulseSpeed'] = 0, -- Adjust the pulse speed as needed
            ['SpinSpeed'] = 1, -- Adjust the spin speed as needed
            ['Dotted'] = false,
            ['Sticky'] = false,
            ['NormalShaped'] = {
                ['Hexagon'] = false,
                ['Triangle'] = false,
                ['Octigon'] = false
            }
        },
        ['Box'] = {
            ['Show'] = false,
            ['Sticky'] = true, -- Recommend
            ['Widith'] = 100,
            ['Height'] = 100,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Rainbow'] = false,
            ['Dotted'] = false,
            ['Predicted'] = true -- Makes the FOV Follow with the Prediction Of your Silent aim
        },
        ['PlayerFOV'] = { -- GUIDE: Player FOV Might seem Tricky at First But it's Just Roblox Avatar Scales (Current Settings Recommended)
            ['Show'] = false,
            ['Height'] = 90/100,
            ['Widith'] = 70/100,
            ['Head'] = 95/100,
            ['Proportions'] = 5/100,
            ['Dotted'] = false
        },
        ['AutoPrediction'] = {
            ['AutoPrediction'] = false,
            ['Delay'] = 0.001259010151111,
            ['AutoPred'] = {
                ['p20_30'] = 0.11,
                ['p30_40'] = 0.12,
                ['p40_50'] = 0.12,
                ['p50_60'] = 0.12,
                ['p60_70'] = 0.129,
                ['p70_80'] = 0.124535
                ['p80_90'] = 0.155,
                ['p90_100'] = 0.191,
                ['p100_110'] = 0.12264,
                ['p110_120'] = 0.1929211135
            },
            ['UsePreCreated'] = {
                ['Enabled'] = false,
                ['PreCreatedAutoPredictionMode'] = 'V.8', -- V.1 V.2 V.3 V.4 V.5 V.6 V.7 V.8
                ['Interval'] = 5.5/10,
                ['Precision'] = 1,
                ['Coefficient'] = 1,
            }
        },
        ['TargetCheck'] = {
            ['Enabled'] = true,
            ['Chance'] = 80
        },
        ['PointRate'] = {
            ['Power'] = 10 -- the More you go down the more harder it is too Hit a Bodypart 6-7 is best
        },
        ['PredictionAnalyzer'] = { -- Makes Sure your Prediction doesnt Predict too far, Current settings are Good
            ['Enabled'] = false,
            ['UniversalPing'] = true, -- KEEP ON
            ['AvoidOuterHitbox'] = true,
            ['Rate'] = 67
        }
    },
    ['TargetAim'] = {
        ['Enabled'] = false,
        ['AirShotFunction'] = true,
        ['Keybind'] = "",
        ['Prediction'] = 0.124878157348769238732897353555555,
        ['AirShotPrediction'] = 0.12485,
        ['Hitpart'] = "Head", -- You can Use All 16 Hitparts For this
        ['AntiGroundShots'] = true,
        ['Size'] = 70, -- FOV
        ['Color'] = Color3fromRGB(200, 1, 200),
        ['Filled'] = false,
        ['Thickness'] = 0.2,
        ['Transparency'] = 0.5,
        ['HighlightTargetedPlayer'] = true
    },
    ['Camlock'] = {
        ['Enabled'] = true,
        ['Keybind'] = "C",
        ['HoldMode'] = false,
        ['MouseMode'] = false,
        ['MouseBind'] = Enum.UserInputType.MouseButton1,
        ['CamlockChecks'] = {
            ['TypeCheck'] = false,
            ['DisableOnThirdPerson'] = false,
            ['DisableOnReload'] = false,
            ['GunCheck'] = false
        }, 
        ['Settings'] = {
            ['ClosestPoint'] = false,
            ['ClosetPart'] = false,
            ['Normal'] = true, -- One Hitpart
            ['Hitpart'] = "UpperTorso",
            ['AirShotHitpart'] = "Head",
            ['CamlockOffsets'] = {
                ['UseOffsets'] = false,
                ['XOffset'] = 0,
                ['YOffset'] = 0
            }
            ['PredictionSettings'] = {
                ['PredictionX'] = 0.135, -- Main Prediction
                ['PredictionY'] = 0.135
            }
        },
        ['FovSettings'] = {
            ['Show'] = true,
            ['Size'] = 50,
            ['Color'] = Color3fromRGB(200, 1, 200),
            ['Filled'] = false,
            ['Thickness'] = 0.2,
            ['Transparency'] = 0.5,
            ['Deadzone'] = false,
            ['DeadzoneSize'] = 15
        },
        ['CamlockModes'] = {
            ['Easing'] = true,
            ['Bezier'] = false,
            ['Hyperbola'] = false,
            ['Cardioid'] = false
        },
        ['EasingSettings'] = {
            ['EasingStyle'] = "Linear",
            ['AirEasingStyle'] = "Sine",
            ['EasingDirection'] = "InOut"
        },
        ['BezierSettings'] = {
            ['T_Threshold'] = 0.99941,
            ['CurvePoints'] = Vector2.new(0, 0) -- X, Y
        },
        ['Hyperbola'] = {
            ['Hyperbola_Sensitivity'] = 4, -- Smoothness
            ['HyperbolaFrequency'] = 0.5,
            ['ActOnRecoil'] = true
        },
        ['Cardioid'] = {
            ['CardioidX'] = 1,
            ['CardioidY'] = 7,
            ['CardioidFrequency'] = 0.5
        },
        ['Other'] = {
            ['FrameSkips'] = false,
            ['FrameSkipKeybind'] = "",
            ['ShakeSettings'] = {
                ['Shake'] = false,
                ['Shake_X'] = 1,
                ['Shake_Y'] = 1,
                ['Shake_Z'] = 1,
                ['ShakeOffsetX'] = 0,
                ['ShakeOffsetY'] = 0
            }
        }
    },
    ['TriggerBot'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['MouseMode'] = false,
        ['MouseBind'] = Enum.UserInputType.MouseButton2,
        ['DisableWhenKnife'] = true,
        ['HoldMode'] = false,
        ['PredictionMode'] = {
            ['Enabled'] = true,
            ['Prediction'] = 0.12,
        },
        ['TriggerBotFOV'] = {
            ['UseFov'] = true,
            ['UseBox'] = false,
            ['BoxWidith'] = 55,
            ['BoxHeight'] = 55,
            ['Size'] = 30,
        },
        ['TriggerBotRangeSettings'] = {
            ['Enabled'] = false,

            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal"
        }
    },
    ['RangeFOVSilent'] = {
        ['Enabled'] = false,
        ['Shotguns'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,

            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100,

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal"

        },
        ['Pistols'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,

            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100,

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal",
        },
        ['Automatics'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.12,
            ['MediumRangePrediction'] = 0.12,
            ['FarRangePrediction'] = 0.12,

            ['CloseRangeFOV'] = 10,
            ['MediumRangeFOV'] = 10,
            ['FarRangeFOV'] = 10,

            ['CloseRangeHitChance'] = 100,
            ['MediumRangeHitChance'] = 100,
            ['FarRangeHitChance'] = 100,

            ['CloseRangeFOVMode'] = "Normal",
            ['MediumRangeFOVMode'] = "Normal",
            ['FarRangeFOVMode'] = "Normal"
        }
    },
    ['RangeFOVCamlock'] = {
        ['Enabled'] = false,
        ['Shotguns'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.155,
            ['MediumRangePrediction'] = 0.155,
            ['FarRangePrediction'] = 0.155,

            ['CloseRangeSmoothness'] = 0.00808,
            ['MediumRangeSmoothness'] = 0.00808,
            ['FarRangeSmoothness'] = 0.00808,

            ['CloseRangeCamlockMode'] = "Easing",
            ['MediumRangeCamlockMode'] = "Easing",
            ['FarRangeCamlockMode'] = "Easing",

            ['CloseRangeEasingStyle'] = "Linear",
            ['MediumRangeEasingStyle'] = "Linear",
            ['FarRangeEasingStyle'] = "Linear",

            ['CloseRangeAirShotEasingStyle'] = "Linear",
            ['MediumRangeAirShotEasingStyle'] = "Linear",
            ['FarRangeAirShotEasingStyle'] = "Linear",

            ['Bezier'] = false,

            ['CloseRangeT_Threshold'] = 0.99941,
            ['MediumRangeT_Threshold'] = 0.99941,
            ['FarRangeT_Threshold'] = 0.99941,

            ['CloseRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
            ['MediumRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
            ['FarRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
        }
        ['Pistols'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.155,
            ['MediumRangePrediction'] = 0.155,
            ['FarRangePrediction'] = 0.155,

            ['CloseRangeSmoothness'] = 0.00808,
            ['MediumRangeSmoothness'] = 0.00808,
            ['FarRangeSmoothness'] = 0.00808,

            ['CloseRangeCamlockMode'] = "Easing",
            ['MediumRangeCamlockMode'] = "Easing",
            ['FarRangeCamlockMode'] = "Easing",

            ['CloseRangeEasingStyle'] = "Linear",
            ['MediumRangeEasingStyle'] = "Linear",
            ['FarRangeEasingStyle'] = "Linear",

            ['CloseRangeAirShotEasingStyle'] = "Linear",
            ['MediumRangeAirShotEasingStyle'] = "Linear",
            ['FarRangeAirShotEasingStyle'] = "Linear",

            ['Bezier'] = false,

            ['CloseRangeT_Threshold'] = 0.99941,
            ['MediumRangeT_Threshold'] = 0.99941,
            ['FarRangeT_Threshold'] = 0.99941,

            ['CloseRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
            ['MediumRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
            ['FarRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
        }
        ['Automatics'] = {
            ['Close'] = 27, -- Studs
            ['Medium'] = 60,
            ['Far'] = math.huge,

            ['CloseRangePrediction'] = 0.155,
            ['MediumRangePrediction'] = 0.155,
            ['FarRangePrediction'] = 0.155,

            ['CloseRangeSmoothness'] = 0.00808,
            ['MediumRangeSmoothness'] = 0.00808,
            ['FarRangeSmoothness'] = 0.00808,

            ['CloseRangeCamlockMode'] = "Easing",
            ['MediumRangeCamlockMode'] = "Easing",
            ['FarRangeCamlockMode'] = "Easing",

            ['CloseRangeEasingStyle'] = "Linear",
            ['MediumRangeEasingStyle'] = "Linear",
            ['FarRangeEasingStyle'] = "Linear",

            ['CloseRangeAirShotEasingStyle'] = "Linear",
            ['MediumRangeAirShotEasingStyle'] = "Linear",
            ['FarRangeAirShotEasingStyle'] = "Linear",

            ['Bezier'] = false,

            ['CloseRangeT_Threshold'] = 0.99941,
            ['MediumRangeT_Threshold'] = 0.99941,
            ['FarRangeT_Threshold'] = 0.99941,

            ['CloseRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
            ['MediumRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
            ['FarRangeCurvePoints'] = Vector2.new(0, 0) -- X, Y
        }
    },
    ['Resolver'] = {
        ['Enabled'] = true,
        ['Mode'] = "Linear" -- Linear, Delta, Basic
    }
    ['Misc'] = {
        ['PanicKey'] = "",
        ['CFrame'] = "", -- 185 Speed
        ['Fly'] = "", -- 145 Speed
    },
    ['Visuals'] = { -- Inside GUI Has Customizable Colors Plus Visualizer
        ['Enabled'] = false,
        ['NameESP'] = false,
        ['BoundingBox'] = false,
        ['HealthBar'] = false,
        ['HealthNumber'] = false,
        ['HeadDot'] = false,
        ['OffscreenArrows'] = false,
        ['GunESP'] = false,
        ['GunChams'] = false,
        ['PlayerChams'] = false,
        ['AnimatedESP'] = false,
        ['FriendlyESP'] = false, -- Highlights Friends
        ['TargetESP'] = false, -- Highlights Targeted Players
        ['TargetedPlayerName'] = "Byfron", -- Username
        ['AnimateESP'] = false,
        ['PlayerDistance'] = false
    },
    ['RaidAwareness'] = {
        ['Enabled'] = false,
        ['Keybind'] = "", -- Toggle Onto your Targeted Player
        ['KillSwitch'] = "",

        ['Username1'] = "",
        ['Username2'] = "",
        ['Username3'] = "",
        ['Username4'] = "",
        ['Username5'] = "",
        ['Username6'] = "",
        ['Username7'] = "",
        ['Username8'] = "",
        ['Username9'] = "",
        ['Username10'] = ""
    },
    ['AntiAim'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['AntiLockMode'] = "PredictionBreaker" -- PredictionBreaker, InvisibleDesync, Desync, Underground, Sky, Network, Walkable
    },
    ['FFLAG'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['FFLAGMode'] = "InvisibleDesync" -- Underground, InvisibleDesync, Jitter, Network
    },
    ['RapidFire'] = { -- more Universal within Gui
        ['Enabled'] = false,
        ['Rate'] = 10
    },
    -- Error loggers If you Know you know I'd Recommend too not touch
    -- Credits too Stefanuk for Helping me On this
    -- checks for any errors
    export type ErrorLogger = {
        ErrorCheck: boolean | "error" | "kick",
        DisableIfSpeedAbove: 10, -- Recommend too Keep On 10 Test For yourself
        ['Enabled'] = false,
        ['Print'] = false, -- Would Use if Your testing
        ['PrintMessage'] = "ERROR NIGGA! FIX UR CONFIG FUCK BOY",
        ['Delay'] = 1 -- In seconds
    },
    ['FeatureList'] = { -- Pops up a Ui on your Lefthand Side of your screen. shows what you have enabled and not, you can add stuff aswell
        ['Enabled'] = false,
        {SilentAimAxis = {}, ClosestPoint = {}, ReductionRate = {}, Beizer = {}, Cardioid = {}, Easing = {}},
    },
    ['TrashTalk'] = {
        ['Enabled'] = false,
        ['Keybind'] = "",
        ['LastTick'] = tick(), -- Dont touch
        ['Delay'] = 0.01,
        ['Messages'] = {
            "Serpent is Better",
            "🤡🤡🤡🤡",
            "Lol Cant Beat me",
            "My Triggerbot is 1#",
            "*Slithers*",
            "🐍🐍🐍🐍🐍",
            "Ur script is pasted",
            "Lol Shitty nemesis user",
            "🐍🐍 .gg/serpent.cc"
        }
    },
    ['DestroyCheaters'] = {
        ['Enabled'] = false,
        ['Keybind'] = ""
    },
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/e14209cacb6973d3e605234db8583c52.lua"))()  
